version: "3"

services:
  myopencv:
    build: ./
    volumes:
      - ../:/mnt
    tty: true
    working_dir: /mnt/10_05_pkg-config
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
